### ISSUE TITLE
Building doesnt actually build

### ISSUE THREAD

**Issue by jaxgeller** [callmecavs/outset#10]
Under `gulp.task('build', ['html', 'sass', 'js', 'images', 'fonts',...])` every task builds then exits except js. Thus if you ever need to build and exit, you must manually intervene. I believe this is because of watchify. It would be great if we can get back the ability to run `gulp build` and have it exit once completed.

**Comment by callmecavs** [comment]
definitely doable with a separate JS task that runs `browserify` directly, rather than through `watchify`. will take some finesse to get a solution thats elegant and DRY - open to a PR if you'd like to take a crack at it

**Comment by jaxgeller** [comment]
Was this fixed?

**Comment by callmecavs** [comment]
@jaxgeller yes
