### ISSUE TITLE
Use cssnano

### ISSUE THREAD

**Issue by jaxgeller** [callmecavs/outset#11]
`gulp-minify-css@1.2.2: Use better "gulp-cssnano" instead. https://github.com/ben-eb/gulp-cssnano`

Or even better use `libsass output: compressed`

**Comment by callmecavs** [comment]
:ok_hand:

**Comment by jaxgeller** [comment]
One less dependency is a win in my book.

**Comment by callmecavs** [comment]
fixed in the latest release

commit for reference: https://github.com/callmecavs/outset/commit/a598a03d7e7ee866ad02c0df2aaf76babf771a21 :beers:

**Comment by callmecavs** [comment]
pretty sure libsass' compressed mode simply removes whitespace, whereas cssnano runs optimizations on the compiled Sass. let me know if your testing reveals otherwise brotha

**Comment by jaxgeller** [comment]
Ran a benchmark for reference, 

```
cssmin: 35584 (35k)
output-compressed: 47795 (47k)
cssnano: 36957 (36k)
```

**Comment by callmecavs** [comment]
thanks for posting those here. funny how cssmin is achieving lower file size, but I'd imagine its because of some unsafe optimizations. anyways, since its deprecated, cssnano it is
